#!/bin/sh
set -e
# Automatically added by dh_systemd_start/10.7.2ubuntu2
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop vpp.service >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/10.7.2ubuntu2
if [ -x "/etc/init.d/vpp" ]; then
	invoke-rc.d vpp stop || exit $?
fi
# End automatically added section
